name: Release NodeJS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v2

      - name: Configurar o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar a imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login no Render.com
        run: render login --github-token ${{ secrets.GITHUB_TOKEN }}

      - name: Render.com
        run: render create --docker-image ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.sha }} --name app

      - name: Deploy Render.com
        run: render deploy --name app

